# fly.toml app configuration file generated for bike-ride-planner on 2025-05-30T18:31:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bike-ride-planner'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
